const CONFIG = {
    introTitle: 'hello ank:3',
    introDesc:'hjhj ',
    btnintro:'ấn ',
    title: 'ank có yêu em không ??',
    desc: 'thoát ra là làm chồng em luôn nka đcm ',
    btnYes: 'yêu em vailon:3',
    btnNo: 'đéo :)  :3',
    question:'đcm bây giờ ank có làm ngyeu em không thì bảo :)',
    btnReply: 'Gửi ',
    reply: 'có chứ :3 Yêu em vailon ý ',
    mess: 'em biết mà 🥰. Yêu ank hehehehe ',
    messDesc: 'tròi oi ib cho em đi chứ còn chừ gì nữa :3.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://www.facebook.com/camhadangiu
